openapi: "3.0.2"
info:
  title: Hello
  version: "1.0"
servers:
  - url: http://localhost:7071/api/
    description: Localhost
  - url: https://stcu-hello.azurewebsites.net/api/
    description: App Function
  - url: https://stcu-hello-apim.azure-api.net/hello-one/
    description: APIM
paths:
  /HelloOne:
    get:
      parameters:
        - in: query
          name: name
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              example: Hello Alice
            application/json:
              example: { message: Hello Alice }
