openapi: "3.0.2"
info:
  title: Hello
  version: "1.0"
servers:
  - url: http://localhost:7071/api/
paths:
  /HelloOne:
    get:
      parameters:
        - in: query
          name: name
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              example: Hello Alice
