openapi: "3.0.2"
info:
  title: Test API
  version: "1.0"
servers:
  - url: https://muledev/
    description: Description
  - url: https://localhost/
security:
  - BasicAuth: []
components:
  parameters:
    health:
      name: health
      in: query
      required: true
      description: Capture input
      schema:
        type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
paths:
  /health-check:
    get:
      description: Gets the health
      responses:
        "200":
          description: OK

    post:
      description: Posting
      responses:
        "200":
          description: OK
