name: AzureFunctionDeploy
on:
    push:
        paths:
            - 'functions/**'

# https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/windows-dotnet-functionapp-on-azure-rbac.yml

env:
    AZURE_FUNCTIONAPP_NAME: Hello
    AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions'
    DOTNET_VERSION: '3.1.103'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@master

            - name: 'Login via Azure CLI'
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: 'Run dotnet'
              shell: pwsh
              run: |
                  pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
                  dotnet build --configuration Release --output ./output
                  popd

            - name: 'Run Azure Functions Action'
              uses: Azure/functions-action@v1
              id: fa
              with:
                  app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                  package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
